### ISSUE TITLE
ERROR - 67 Invalid private key

### ISSUE THREAD

**Issue by trubarr** [wildbunny/bitcoinTradingFramework#4]
There is an error 67 Invalid private key on sell/buy order.

**Comment by wildbunny** [comment]
Are you sure your private key is correct and active?

**Comment by trubarr** [comment]
Huobi Access Key and Secret Key are 100% correct. Other methods are working.

**Comment by wildbunny** [comment]
Those api functions work ok for me, I am able to place orders. However, I am using order_info with an invalid order id from within the Huobi constructor, this will generate an error code 67 - the reason for this intentional error is to get the latest huobi clock time, which isn't available anywhere else but the error message. Could it be this you are seeing?

**Comment by trubarr** [comment]
No. I modified Console write code that it writes method. Method is sell (or buy)
 Console.WriteLine(method + " Huobi error: " + e.m_error.code); 

Any idea what is wrong?

**Comment by trubarr** [comment]
No. I modified Console write code that it writes method. Method is sell (or buy)
Console.WriteLine(method + " Huobi error: " + e.m_error.code);

Any idea what is wrong?

**Comment by wildbunny** [comment]
Is your api key enabled in huobi - that's the only thing I can think of. I'm actually running this code right now with no problems.

**Comment by trubarr** [comment]
Yes it is. Bot cancel orders successfully and wallet informations are correct. 
I googled about that error. What if there is something wrong with self signed certificate.

I added line in code:

System.Net.ServicePointManager.ServerCertificateValidationCallback = delegate(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) { return true; }; 

from

http://sevennet.org/2014/12/08/how-to-could-not-establish-trust-relationship-for-ssltls-secure-channel-soap/

Well it did not help.

On Houbi documentation is written:
Trade API only supports https requests.

Is that my problem? How do I solve it? Thank you.

**Comment by wildbunny** [comment]
The code already uses https for the post api. I suggest trying to find another huobi bot which you can use your API keys with in order to confirm that there isn't anything wrong with your account.

**Comment by wildbunny** [comment]
Hang on a moment - did you say that Huobi.GetAccountInfo() is working ok for you?

**Comment by trubarr** [comment]
Yes GetAccountInfo()  is working.
I try it in HTS bot (https://www.haasonline.com/) and there is working just fine.

**Comment by wildbunny** [comment]
GetAccountInfo() uses your private key, so the huobi error message is probably referring to something else - their docs are sometimes wrong. Check the price you placing your order at is not too far away from the bid/ask, there are limits for low volume orders.

**Comment by trubarr** [comment]
Could it be the decimal values?! Instead of comma(,) it should be dot(.)

Thank you for your help.

**Comment by Addymaddy** [comment]
Hi guys , 

I am new to huobi API and the documentation is mostly in Chinese , can someone tell me from where can I get access key and private key to access the API using http post . 
Right now , I am receiving the error code 67 from huobi I.e . private key authentication failed .

I have used : 

HUOBI_ACCESS_KEY = "使用前请在Base类里配置自己的";
HUOBI_SECRET_KEY = "和";

Any help is much appreciated .
